# SPDX-License-Identifier: CC0-1.0

name: Compile Sketches
on:
  push:
    paths:
      - compile-sketches.ps1
      - '[0-9]/sketches/**'
    tags-ignore: ['**']
  pull_request:
    paths:
      - compile-sketches.ps1
      - '[0-9]/sketches/**'
    tags-ignore: ['**']

jobs:
  check-sketches:
    name: Check compilation of sketches
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: 0.21.x

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile all sketches with Arduino CLI
        shell: pwsh
        run: ./compile-sketches.ps1
