name: Build Slides

on:
  push:
    paths:
      - '.latexmkrc'
      - 'common/**'
      - '[0-9]/**'
  pull_request:
    paths:
      - '.latexmkrc'
      - 'common/**'
      - '[0-9]/**'

# A workflow is made up of one or more jobs that run sequentially or in parallel
jobs:
  build-texlive:
    name: Build slides with TeX Live
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build all slides with latexmk
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add py-pygments
            latexmk
