# SPDX-License-Identifier: CC0-1.0

name: Build and Release Slides
on:
  push:
    paths:
      - '.latexmkrc'
      - 'common/**'
      - '[0-9]/**'
  pull_request:
    paths:
      - '.latexmkrc'
      - 'common/**'
      - '[0-9]/**'
    tags-ignore: ['**']

jobs:
  build-and-release-if-tag:
    name: Build slides; Release if run on tag push
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for release action

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build slides with TeX Live and Latexmk
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add py-pygments
            latexmk -verbose

      - name: Release generated slides if run on tag push
        if: github.ref_type == 'tag' && success()
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: '[0-9]/[0-9].pdf'
          # name: ${{ github.ref_name }}
